language: c

before_install:
 - sudo apt-get -y update
 - sudo apt-get -y install linux-headers-generic
 - git submodule update --init

script:
 - sudo ln -sf $(ls /lib/modules | sed 1q) /lib/modules/$(uname -r)
 - make

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
